// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:2ed7472f-9d5e-4e40-b843-b10f36b1ee2d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_2isFWBMxC",
    "aws_user_pools_web_client_id": "alsi3n4q51h8c9pc5m73h7e1p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zlz23a7gbjcvzompeh3en6kuwm.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "amplify-images-bucket-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "amplifyhost-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://amplifyhost-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
